services:
  flathack-servicehub:
    image: ghcr.io/flathack/stevens-support-app:latest
    container_name: flathack-servicehub
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5000:5000"
    volumes:
      - flathack-servicehub-data:/data

volumes:
  flathack-servicehub-data:
